---
title: "NB_phenmods"
author: "Alden Sears"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(666)
library(tidyverse)
library(dplyr)
library(deSolve)
library(modelr)
library(brms)
library(tidybayes)
library(cmdstanr)
library(posterior)
library(rstan)
library(msm)
```

```{r Part 1: Nicholson-Bailey model from Doebeli 1997}
NBM <- function(t, y, parms){
  
  NBMres <- tibble(Time = c(t), Prey = c(t), Pred = c(t))
  prey <- y["prey"]
  pred <- y["pred"]
  lambda <- parms["lambda"]
  search <- parms["search"]
  conv <- parms["conv"]
  
  # lambda = prey growth rate
  # search = predator search efficiency
  # conv = conversion rate of prey consumed to predators birthed
  
  for (i in 1:length(t)){
    NBMres$Prey[i] <- prey
    NBMres$Pred[i] <- pred
    prey <- lambda * prey * exp(-search * pred)
    pred <- conv * NBMres$Prey[i] * (1-exp(-search * pred))
  }
  
  return(NBMres)
}

time <- seq(from = 1,to = 20, by = 1)
init <- c(prey = 40, pred = 15)
pars <- c(lambda = 2, search = 0.05, conv = 0.5)
out <- NBM(time, init, pars)
out$dPred <- c(0, out$Pred[2:length(out$Pred)] - out$Pred[1:length(out$Pred)-1])

plot(Prey ~ Time, type = "l", data = out, ylim = c(0,max(Prey)))
lines(out$Time, out$Pred, lty = "dashed")
plot(dPred ~ Time, type = "l", data = out)
```

```{r Part 2: Khan & Qureshi 2015 modified NBM}
mNBM <- function(t, y, parms){
  mNBMres <- tibble(Time = c(t), Host = c(t), Para = c(t))
  host <- y["host"]
  para <- y["para"]
  a <- parms["a"]
  b <- parms["b"]
  c <- parms["c"]
  d <- parms["d"]
  # a = attack rate
  # b = unparasitized host birth rate
  # c = hatch rate of parasitoid
  # d = density dependence factor of host
  
  for (i in 1:length(t)){
    mNBMres$Host[i] <- host
    mNBMres$Para[i] <- para
    host <- b * host * exp(-a * para) / (1 + d * host)
    para <- c * mNBMres$Host[i] * (1 - exp(-a * para))
  }
  
  return(mNBMres)
}

time <- seq(1, 100, 1)
init <- c(host = 40, para = 15)
pars <- c(a = 0.1, b = 2, c = 0.5, d = 0.02)

# d of 0.008 leads to stabilization after several cycles of decreasing amplitude
# d of 0.002 leads to parasitoid extinction and host reaches carrying capacity
# intermediate values of d allow for cycles of varying trends in amplitude (sometimes stable, sometimes increasing, sometimes decreasing)

res <- mNBM(time, init, pars)
res$dPara <- c(0, res$Para[2:length(res$Para)] - res$Para[1:length(res$Para)-1])

plot(Host ~ Time, type = "l", data = res, ylim = c(0,max(Host)))
lines(res$Time, res$Para, lty = "dashed")
plot(dPara ~ Time, type = "l", data = res)
plot(dPara ~ Para, type = "l", data = res)

# equation at the end of the paper could be coded as a check for stability—indicates the stability of a local equilibrium point given values of a, b, c, and d
```

```{r Part 3: Growth rate vs pop size}
a <- 0.1
b <- 2
c <- 0.5
d <- 0.02
h <- 0.2
n <- 1e3

NBI <- function(a, c, host, para){
  out <- rnorm(1, c * host * (1 - exp(-a * para)) / para, 0.1)
  # this is the per-capita growth rate of the parasite population
}
NBII <- function(a, c, h, host, para){
  out <- rnorm(1, c * host * (1 - exp((-a * para)/(1 + a * h * host))) / para, 0.1)
  # ditto
}

NBIdat <- tibble(host = rep(24, n),
                 para = sample(0:100, size = n, replace = TRUE)) %>%
  mutate(y = map2_dbl(.x = host, .y = para,
                              .f <- ~NBI(host = .x, para = .y, a = a, c = c)))

NBIIdat <- tibble(host = rep(24, n),
                  para = sample(0:100, size = n, replace = TRUE)) %>%
  mutate(y = map2_dbl(.x = host, .y = para,
                              .f <- ~NBII(host = .x, para = .y, a = a, c = c, h = h)))

plot(y ~ para, data = na.omit(NBIdat))
abline(h = 1)
plot(y ~ para, data = na.omit(NBIIdat))
abline(h = 1)
#library(ggplot2)
#ggplot(NBIdat, aes(x = host, y = para, fill = y)) +
#  geom_tile()

LVform <- as.formula(y ~ lami * (1 - aii * para))
lvformbrms <- bf(LVform, lami ~ 1, aii ~ 1, nl = TRUE)
get_prior(lvformbrms, data = NBIdat, family=gaussian())
lvpriors <- prior(normal(20,100), nlpar = "lami", lb = 0)+
  prior(uniform(-1,1), lb = -1, ub = 1, nlpar = "aii")

#lvpriorcheck <- brm(lvformbrms,
#                  data = NBIdat,
#                  family = gaussian(),
#                  prior = lvpriors,
#                  backend = "cmdstanr", cores = 6,
#                  sample_prior = "only")
#lvpriorcheck

lvpostI <- brm(lvformbrms,
              data = NBIdat,
              family = gaussian(),
              prior = lvpriors,
              backend = "cmdstanr", cores = 6)

#print(summary(lvpostI), digits = 5)

rickform <- as.formula(y ~ lami * exp(-aii * para))
rickformbrms <- bf(rickform, lami ~ 1, aii ~ 1, nl = TRUE)
rickpriors <- prior(normal(20,100),lb=0,nlpar="lami")+
  prior(uniform(-1,1),lb=-1,ub=1,nlpar="aii")

rickpostI <- brm(rickformbrms,
                data = NBIdat,
                family = gaussian(),
                prior = rickpriors,
                backend = "cmdstanr", cores = 6)

#print(summary(rickpostI), digits = 5)

bhform <- as.formula(y ~ lami/(1 + aii * para))
bhformbrms <- bf(rickform, lami ~ 1, aii ~ 1, nl = TRUE)
bhpriors <- prior(normal(20,100),lb=0,nlpar="lami")+
  prior(uniform(-1,1),lb=-1,ub=1,nlpar="aii")

bhpostI <- brm(bhformbrms,
              data = NBIdat,
              family = gaussian(),
              prior = bhpriors,
              backend = "cmdstanr", cores = 6)

#print(summary(bhpostI), digits = 5)

lvpostII <- brm(lvformbrms,
              data = NBIIdat,
              family = gaussian(),
              prior = lvpriors,
              backend = "cmdstanr", cores = 6)

rickpostII <- brm(rickformbrms,
              data = NBIIdat,
              family = gaussian(),
              prior = rickpriors,
              backend = "cmdstanr", cores = 6)

bhpostII <- brm(bhformbrms,
                data = NBIIdat,
                family = gaussian(),
                prior = bhpriors,
                backend = "cmdstanr", cores = 6)

# don't forget to do some checks. solve the equation to find the equilibrium point, plot things to see if they line up with equilibria

curve(c * 24 * (1 - exp(-a * x)) / x, from = 0, to = 100, ylab = "Per-capita growth rate of parasitoid", xlab = "Parasitoid population density")
curve(fixef(lvpostI)[1] * (1 - fixef(lvpostI)[2] * x), add = TRUE, lty = "dashed")
curve(fixef(rickpostI)[1] * exp(-fixef(rickpostI)[2] * x), add = TRUE, lty = "dotted")
curve(fixef(bhpostI)[1]/(1 + fixef(bhpostI)[2] * x), add = TRUE, lty = "dotdash")
legend("topright",legend = c("True relationship","LV model","Ricker model","BH model"),lty = c("solid","dashed","dotted","dotdash"))
curve(c * 24 * (1 - exp((-a * x)/(1 + a * h * 24))) / x, from = 0, to = 100, ylab = "Per-capita growth rate of parasitoid", xlab = "Parasitoid population density")
curve(fixef(lvpostII)[1] * (1 - fixef(lvpostII)[2] * x), add = TRUE, lty = "dashed")
curve(fixef(rickpostII)[1] * exp(-fixef(rickpostII)[2] * x), add = TRUE, lty = "dotted")
curve(fixef(bhpostII)[1]/(1 + fixef(bhpostII)[2] * x), add = TRUE, lty = "dotdash")
legend("topright",legend = c("True relationship","LV model","Ricker model","BH model"),lty = c("solid","dashed","dotted","dotdash"))
```

```{r Part 4: 2 species toybox (following Comins & Hassell (1996))}
tomb <- function(t, y, parms){
  tombres <- tibble(Time = c(t), Host = c(t), P1 = c(t), P2 = c(t))
  host <- y["host"]
  p1 <- y["p1"]
  p2 <- y["p2"]
  a <- 0.1
  b <- parms["b"]
  c1 <- parms["c1"]
  c2 <- parms["c2"]
  d <- parms["d"]
  # a = attack rate
  # b = unparasitized host birth rate
  # c1 = hatch rate of parasitoid 1
  # c2 = hatch rate of parasitoid 2
  # d = density dependence factor of host
  
  for (i in 1:length(t)){
    tombres$Host[i] <- host
    tombres$P1[i] <- p1
    tombres$P2[i] <- p2
    host <- b * host * exp(-a * (p1 + p2)) / (1 + d * host)
    p1 <- c1 * tombres$Host[i] * (1 - exp(-a * p1)) * exp(-a * p2)
    p2 <- c2 * tombres$Host[i] * (1 - exp(-a * p2)) * exp(-a * p1)
  }
  return(tombres)
}

time <- seq(1, 100, 1)
init <- c(host = 100, p1 = 3, p2 = 5)
pars <- c(b = 2, c1 = 0.592, c2 = 0.6, d = 0.02)

ded <- tomb(time,init,pars)

plot(Host ~ Time, data = ded, type = "l", ylim = c(0,max(ded$Host)))
lines(ded$Time, ded$P1, lty = "dashed")
lines(ded$Time, ded$P2, lty = "dotdash")
```

```{r Part 5: 2 species sim}
a <- 0.1
b <- 2
c1 <- 0.592
c2 <- 0.6
d <- 0.02
h <- 0.2
n <- 1e3
hosts <- 100

NB2I <- function(a, c1_or_2, host, para1_or_2, para2_or_1){
  out <- rtnorm(1, c1_or_2 * host * (1 - exp(-a * para1_or_2)) * exp(-a * para2_or_1) / para1_or_2, 0.001, lower = 0)
}
NB2Idat <- tibble(Host = rep(hosts, n),
                  Para1 = sample(1:100, size = n, replace = TRUE),
                  Para2 = sample(1:100, size = n, replace = TRUE)) %>%
  mutate(y1 = map2_dbl(.x = Para1, .y = Para2,
                       .f = ~NB2I(para1_or_2 = .x, para2_or_1 = .y, host = hosts, a = a, c1_or_2 = c1))) %>%
  mutate(y2 = map2_dbl(.x = Para2, .y = Para1,
                       .f = ~NB2I(para1_or_2 = .x, para2_or_1 = .y, host = hosts, a = a, c1_or_2 = c2)))

lv1form <- bf(as.formula(y1 ~ r1 * (1 - a11 * Para1 - a12 * Para2)), r1 ~ 1, a11 ~ 1, a12 ~ 1, nl = TRUE)
lv2form <- bf(as.formula(y2 ~ r2 * (1 - a22 * Para2 - a21 * Para1)), r2 ~ 1, a22 ~ 1, a21 ~ 1, nl = TRUE)
get_prior(lv1form, NB2Idat, gaussian())
lv1priors <- prior(normal(20,100), nlpar = r1, lb = 0) +
  prior(uniform(-1,1), ub = 1, lb = -1, nlpar = a11) +
  prior(uniform(-1,1), ub = 1, lb = -1, nlpar = a12)
lv2priors <- prior(normal(20,100), nlpar = r2, lb = 0) +
  prior(uniform(-1,1), ub = 1, lb = -1, nlpar = a22) +
  prior(uniform(-1,1), ub = 1, lb = -1, nlpar = a21)
lvm1 <- brm(lv1form, NB2Idat,
            family = gaussian(),
            backend = "cmdstanr", cores = 6,
            prior = lv1priors)
lvm2 <- brm(lv2form, NB2Idat,
            family = gaussian(),
            backend = "cmdstanr", cores = 6,
            prior = lv2priors)

Nd <- 1 - sqrt(fixef(lvm1)[3] * fixef(lvm2)[3] / (fixef(lvm1)[2] * fixef(lvm2)[2]))
Fd <- fixef(lvm1)[1] / fixef(lvm2)[2] * sqrt(fixef(lvm2)[2] * fixef(lvm2)[3] / (fixef(lvm1)[2] * fixef(lvm1)[3]))
Nd > Fd
```

```{r Part 6: 2 species with substitutable resource}

```







































