---
title: "SimModsPrax"
author: "Alden Sears"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Simulation of continuous-time LV data}
library(deSolve)
library(cmdstanr)
library(rstan)
library(rethinking)
library(posterior)
library(dplyr)
LVM <- function (t, init, pars) {
    with(as.list(c(init, pars)), {
        dx = r1*(1-a11*x-a12*y)
        dy = r2*(1-a22*y-a21*x)
        return(list(c(dx, dy)))
    })
}
t<-seq(0,1000,by=1)
init<-c(x=10,y=10)
pars1<-c(r1=0.3,r2=0.4,a11=0.0025,a22=0.003,a12=0.0015,a21=0.001)
out1<-as.data.frame(ode(func=LVM,y=init,parms=pars1,times=t))

pars2<-c(r1=0.3,r2=0.4,a11=0.0015,a22=0.03,a12=0.06,a21=0.03)
out2<-as.data.frame(ode(func=LVM,y=init,parms=pars2,times=t))

matplot(out2[,-1], type = "l", xlab = "time", ylab = "population")
legend("topright", c("Species 1", "Species 2"), lty = c(1,2), col = c(1,2), box.lwd = 0)

#next:
#build a bayesian workflow to construct the beverton-holt competition equations using the capital T data.
#incorporate the generating mechanism and the fitting mechanism into a smooth function that takes parameter values
#and yields a comparison of results
```

```{r Simulate data the WKP way}
library(tidyverse)
library(nlstools)
library(brms)
library(tidybayes)
library(modelr)

set.seed(666)
lvform<-as.formula(y~lami*(1-aii*Ni-aij*Nj))
lvnorm<-function(lami,aii,Ni,aij,Nj,sd){
  out<-rnorm(n=1,mean=(lami*(1-aii*Ni-aij*Nj)),sd=sd)
  return(out)
}

lami<-30
aii<-0.0078
aij<-0.0057
sd<-5
n<-100

lvdat<-tibble(Ni=sample(0:100,size=n,replace=TRUE),
              Nj=sample(0:100,size=n,replace=TRUE)) %>%
  mutate(.data=lvdat,y=map2_dbl(.x=Ni,.y=Nj,
                              .f<-~lvnorm(Ni=.x,Nj=.y,lami=lami,sd=sd,aij=aij,aii=aii)))

plot(Ni~Nj,data = lvdat)
```

```{r Modeling in nls}
lvnls<-nls(lvform,data=lvdat,start = list(lami=10,aii=0.002,aij=0.002))
summary(lvnls)

plot(profile(lvnls))
overview(lvnls)
summary(nlsJack(lvnls))
```

```{r Modeling in brms}
lvform_brms<-bf(lvform,lami~1,aii~1,aij~1,nl=TRUE)
get_prior(lvform_brms,data=lvdat,family=gaussian())

hist(abs(rnorm(1e6,20,sd=100)),breaks=10000)
lvpriors<-prior(normal(20,100),nlpar="lami",lb=0)+
  prior(uniform(0,0.1),lb=0,ub=0.1,nlpar="aii")+
  prior(uniform(0,0.1),lb=0,ub=0.1,nlpar="aij")

lvpriorcheck<-brm(lvform_brms,
                  data=lvdat,
                  family=gaussian(),
                  prior = lvpriors,
                  backend = "cmdstanr", cores = 6,
                  sample_prior = "only")
lvpriorcheck

lvpost<-brm(lvform_brms,
            data=lvdat,
            family=gaussian(),
            prior=lvpriors,
            backend = "cmdstanr", cores = 6)

print(summary(lvpost),digits=5)

idraws<-lvdat %>%
  data_grid(Ni=0:100,
            Nj=0:100) %>%
  filter(Nj == 0) %>%
  add_epred_draws(lvpriorcheck,ndraws = 50)
pdraws<-lvdat %>%
  data_grid(Ni=0:100,
            Nj=0:100) %>%
  filter(Nj == 0) %>%
  add_epred_draws(lvpost,ndraws = 50)

ggplot(data=NULL,aes(x=Ni,y=.epred,group=.draw))+
  geom_line(data=idraws,color="red",alpha=0.75)+
  geom_line(data=pdraws,color="blue",alpha=0.75)
```

```{r Bonus: do ricker}
rickform<-as.formula(y~lami*exp(-aii*Ni-aij*Nj))
ricknorm<-function(lami,aii,Ni,aij,Nj,sd){
  out<-rnorm(n=1,mean=(lami*exp(-aii*Ni-aij*Nj)),sd=sd)
  return(out)
}

#Simulate Ricker stuff

lami<-300
aii<-0.034
aij<-0.024
sd<-5
n<-100

rickdat<-tibble(Ni=sample(0:100,size=n,replace = TRUE),
                Nj=sample(0:100,size=n,replace = TRUE)) %>%
  mutate(y=map2_dbl(.x=Ni,.y=Nj,.f=~ricknorm(Ni=.x,Nj=.y,lami=lami,aii=aii,aij=aij,sd=sd)))

#nls model

ricknls<-nls(rickform,rickdat,start=list(lami=200,aii=0.05,aij=0.05))
ricknls
overview(ricknls)

#brms model

rickbrms<-bf(rickform,lami~1,aii~1,aij~1,nl=TRUE)
get_prior(rickbrms,family=gaussian(),data=rickdat)

rickpriors<-prior(normal(1000,5000),lb=0,nlpar="lami")+
  prior(uniform(0,0.1),lb=0,ub=0.1,nlpar="aii")+
  prior(uniform(0,0.1),lb=0,ub=0.1,nlpar="aij")

#check priors

prioricky<-brm(rickbrms,
               data=rickdat,
               family=gaussian(),
               sample_prior = "only",
               backend = "cmdstanr", cores = 6,
               prior=rickpriors)
prioricky

postrick<-brm(rickbrms,
              data=rickdat,
              family=gaussian(),
              backend = "cmdstanr",cores=6,
              prior=rickpriors)
print(summary(postrick),digits=5)
```

```{r}
gen_gen <- function(spi,rs,N,alpha_mat,model,obs_error_dist,...){
  # checks
  if (is.character(spi) == FALSE){
    stop("object 'spi' object not of type 'character'")
  } else if (is.vector(rs) == FALSE){
    stop("object 'rs' not of type 'vector'")
  } else if (is.vector(N) == FALSE){
    stop("object 'N' not of type 'vector'")
  } else if (is.matrix(alpha_mat) == FALSE){
    stop("object 'alpha_mat' not of type 'matrix'")
  } else if (model %in% c("LV","BH","R") == FALSE){
    stop("specified model 'model' must be one of 'LV' (Lotka-Volterra), 'BH' (Beverton-Holt), or 'R' (Ricker)")
  } else if (length(rs) != length(N) | nrow(alpha_mat) != ncol(alpha_mat) | length(N) != nrow(alpha_mat)){
    stop("vector lengths and alpha_mat row and column lengths must all be equal")
  } else if (spi %in% rownames(alpha_mat) == FALSE){
    stop("focal species 'spi' must have the same name as one of the rows in 'alpha_mat'")
  } else if ((names(rs) != rownames(alpha_mat))[1] | (names(N) != rownames(alpha_mat))[1]){
    stop("'rs' and 'N' names must match the row names of 'alpha_mat'")
  } else if (missing(obs_error_dist) == FALSE){
    if (obs_error_dist %in% c("normal","poisson","nb") == FALSE){
      stop("specified observation error distribution 'obs_error_dist' must be one of 'normal', 'poisson', or 'nb'")
    }
  }
  # now the actual operations
  comp_coef <- alpha_mat %*% N
  if (model == "LV"){
    fecund <- ((1-comp_coef[spi,]) %*% rs[spi])
  } else if (model == "BH"){
    fecund <- (1/(1+comp_coef[spi,]) %*% rs[spi])
  } else if (model == "R"){
    fecund <- (exp(-comp_coef[spi,]) %*% rs[spi])
  }
  if (missing(obs_error_dist)){
    return(as.numeric(fecund))
  } else if (obs_error_dist == "normal"){
    return(rnorm(n=1, mean=fecund, sd=...))
  } else if (obs_error_dist == "poisson"){
    return(rpois(1,lambda = fecund))
  }
}

# time to simulate data: choose rs, alpha_mat, N
spi <- "a"
rs <- c("a"=50,"b"=68,"c"=25)
N <- c("a"=30,"b"=24,"c"=41)
alpha_mat <- matrix(c(0.0078,0.0056,0.0034,0.0067,0.005,0.0016,0.0053,0.007,0.0034),ncol=3,byrow = TRUE,
                    dimnames = list(c("a","b","c"),c("a","b","c")))
multi_dat <- gen_gen(spi=spi,rs=rs,N=N,alpha_mat=alpha_mat,model = "LV")
multi_dat_oe <- gen_gen(spi=spi,rs=rs,N=N,alpha_mat=alpha_mat,model = "LV",obs_error_dist = "normal",sd=1)

# AHAHAHAHA IT WORKSSS!!!
set.seed(666)

spi <- "a"
rs <- c("a"=50,"b"=68,"c"=25,"d"=14)
alpha_mat <- matrix(c(0.0078,0.0056,0.0034,0.0048,0.0067,0.005,0.0016,0.0087,
                      0.0053,0.007,0.0034,0.0024,0.0054,0.004,0.0031,0.0017),
                    ncol=4,byrow=TRUE,dimnames=list(c("a","b","c","d"),c("a","b","c","d")))
model <- "LV"
obs_error_dist <- "normal"
sd=1

Na=sample(1:100, size = 100, replace = TRUE)
Nb=sample(1:100, size = 100, replace = TRUE)
Nc=sample(1:100, size = 100, replace = TRUE)
Nd=sample(1:100, size = 100, replace = TRUE)
names(Na)<-rep("a",100)
names(Nb)<-rep("b",100)
names(Nc)<-rep("c",100)
names(Nd)<-rep("d",100)

multi <- tibble(Na,Nb,Nc,Nd,y=NA)
for (i in 1:length(multi$Na)){
  multi$y[i] <- gen_gen(spi=spi,rs=rs,N=c(multi$Na[i],multi$Nb[i],multi$Nc[i],
                        multi$Nd[i]),alpha_mat=alpha_mat,model=model,obs_error_dist=obs_error_dist,sd=sd)
}

# next: a generating function that can write brms-compatible functions with nl parameters,
# for any number of species and for any choice of dynamics

bfwriter <- function(nspec,spi,dynam){
  multilist <- list("a"=c("aaa*Na","aab*Nb","aac*Nc","aad*Nd","aae*Ne","aaf*Nf","aag*Ng","aah*Nh","aai*Ni","aaj*Nj"),
                  "b"=c("aba*Na","abb*Nb","abc*Nc","abd*Nd","abe*Ne","abf*Nf","abg*Ng","abh*Nh","abi*Ni","abj*Nj"),
                  "c"=c("aca*Na","acb*Nb","acc*Nc","acd*Nd","ace*Ne","acf*Nf","acg*Ng","ach*Nh","aci*Ni","acj*Nj"),
                  "d"=c("ada*Na","adb*Nb","adc*Nc","add*Nd","ade*Ne","adf*Nf","adg*Ng","adh*Nh","adi*Ni","adj*Nj"),
                  "e"=c("aea*Na","aeb*Nb","aec*Nc","aed*Nd","aee*Ne","aef*Nf","aeg*Ng","aeh*Nh","aei*Ni","aej*Nj"),
                  "f"=c("afa*Na","afb*Nb","afc*Nc","afd*Nd","afe*Ne","aff*Nf","afg*Ng","afh*Nh","afi*Ni","afj*Nj"),
                  "g"=c("aga*Na","agb*Nb","agc*Nc","agd*Nd","age*Ne","agf*Nf","agg*Ng","agh*Nh","agi*Ni","agj*Nj"),
                  "h"=c("aha*Na","ahb*Nb","ahc*Nc","ahd*Nd","ahe*Ne","ahf*Nf","ahg*Ng","ahh*Nh","ahi*Ni","ahj*Nj"),
                  "i"=c("aia*Na","aib*Nb","aic*Nc","aid*Nd","aie*Ne","aif*Nf","aig*Ng","aih*Nh","aii*Ni","aij*Nj"),
                  "j"=c("aja*Na","ajb*Nb","ajc*Nc","ajd*Nd","aje*Ne","ajf*Nf","ajg*Ng","ajh*Nh","aji*Ni","ajj*Nj"))
  if (nspec > 10 | nspec <= 0){
    stop("'nspec' must be a number between 1 and 10 inclusive")
  }
  if (dynam == "LV"){
    eq <- "formula=as.formula(y~lami*(1"
    for (i in 1:nspec){
      eq <- paste(eq,"-",multilist[[spi]][i],sep="")
    }
    eq <- paste(eq,"))",sep="")
    nlps <- ",nl=TRUE,lami~1"
    for (i in 1:nspec){
      nlps <- paste(nlps,",",substr(multilist[[spi]][i],1,3),"~1",sep="")
    }
    written <- paste(dynam,"multi <- bf(",eq,nlps,")",sep="")
    return(written)
  } else if (dynam == "BH"){
    eq <- "formula=as.formula(y~lami/(1"
    for (i in 1:nspec){
      eq <- paste(eq,"+",multilist[[spi]][i],sep="")
    }
    eq <- paste(eq,"))",sep="")
    nlps <- ",nl=TRUE,lami~1"
    for (i in 1:nspec){
      nlps <- paste(nlps,",",substr(multilist[[spi]][i],1,3),"~1",sep="")
    }
    written <- paste(dynam,"multi <- bf(",eq,nlps,")",sep="")
    return(written)
  } else if (dynam == "R"){
        eq <- "formula=as.formula(y~lami*exp("
    for (i in 1:nspec){
      eq <- paste(eq,"-",multilist[[spi]][i],sep="")
    }
    eq <- paste(eq,"))",sep="")
    nlps <- ",nl=TRUE,lami~1"
    for (i in 1:nspec){
      nlps <- paste(nlps,",",substr(multilist[[spi]][i],1,3),"~1",sep="")
    }
    written <- paste(dynam,"multi <- bf(",eq,nlps,")",sep="")
    return(written)
  } else {
    stop("specify dynam as one of 'LV','BH', or 'R'")
  }
}

get_multi_eq <- function(nspec,spi,dynam){
  eval(parse(text=bfwriter(nspec,spi,dynam)),envir = parent.frame())
}

get_multi_eq(4,"a","LV")
get_prior(LVmulti,family="gaussian",data=multi)

multipriors <- prior(normal(1000,5000),lb=0,nlpar="lami")+
  prior(uniform(0,0.1),lb=0,ub=0.1,nlpar="aaa")+
  prior(uniform(0,0.1),lb=0,ub=0.1,nlpar="aab")+
  prior(uniform(0,0.1),lb=0,ub=0.1,nlpar="aac")+
  prior(uniform(0,0.1),lb=0,ub=0.1,nlpar="aad")
multimod <- brm(LVmulti,data=multi,family=gaussian(),
                backend="cmdstanr",cores=6,prior=multipriors)
print(summary(multimod),digits=5)

# It works and it is HELLA accurate
# Problem: need to coerce gen_gen into giving the resulting seed set (y) for each species as a focal. Then, need to
# modify bfwriter as appropriate to include the correct response variable (not y, but y"spi")
```



















